USE [master]
GO

/****** Object:  Database [college]    Script Date: 29.03.2020 21:58:18 ******/
CREATE DATABASE [college]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'college', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\college.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'college_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\college_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [college].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [college] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [college] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [college] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [college] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [college] SET ARITHABORT OFF 
GO

ALTER DATABASE [college] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [college] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [college] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [college] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [college] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [college] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [college] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [college] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [college] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [college] SET  DISABLE_BROKER 
GO

ALTER DATABASE [college] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [college] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [college] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [college] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [college] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [college] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [college] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [college] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [college] SET  MULTI_USER 
GO

ALTER DATABASE [college] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [college] SET DB_CHAINING OFF 
GO

ALTER DATABASE [college] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [college] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [college] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [college] SET QUERY_STORE = OFF
GO

ALTER DATABASE [college] SET  READ_WRITE 
GO

